### ISSUE TITLE
Problem displaying a region with only one size (width ou hight)

### ISSUE THREAD

**Issue by jeau** [Daniel-KM/Omeka-S-module-ImageServer#1]
This bug appears only for images whose tiles have been generated. 

When requesting a particular region with a particular width or hight and not the other size for output, as follows  
`/iiif-img/id/x0,y0,w0,h0/w1,/0/default.jpg`

you should get an image detail of the same proportion as the requested area and of width `w1` but the server returns a square thumbnail of 256 pixels per side or an error (depending on whether the requested size is greater or less than 800 px).

however, this request with the two sizes works fine :
`/iiif-img/id/x0,y0,w0,h0/w1,h1/0/default.jpg`

I actually have the same problem with the IiifServer module.

Thierry

**Comment by Daniel-KM** [comment]
Ok, it seems to be a true bug.

**Comment by Daniel-KM** [comment]
This is fixed by the beta version. Many other fixes too. Iiif server was updated too.

**Comment by jeau** [comment]
merci
