### ISSUE TITLE
Error: The file is not tiled for dynamic processing

### ISSUE THREAD

**Issue by jeau** [Daniel-KM/Omeka-S-module-ImageServer#2]
This error appears only for images whose tiles have been generated when I trie to display it or get some specific zone. 

'The Image server encountered an unexpected error that prevented it from fulfilling the request: the file is not tiled for dynamic processing.'

thierry

**Comment by Daniel-KM** [comment]
Hi, 
Can I have the full log (https://omeka.org/s/docs/user-manual/errorLogging/) ? Thanks.

**Comment by jeau** [comment]
on server side, I've activated the development env in `.htaccess` and enabled logging, but i saw only this message display on page of my site: `Notice : Undefined variable: user in /var/www/html/dev-horpic/application/view/common/user-bar.phtml on line 9` and there's no particular error in  `logs/application.log` 

on client side, with Tify viewer `closeError loading image: Image load aborted` or `Error loading image: Image load exceeded timeout (30000 ms)` (error 500). With Universar viewer there's no error message but the tiles aren't loaded anymore

**Comment by Daniel-KM** [comment]
Bonjour Jeau,

I probably fixed it in last release of image server and iiif server.
Note that there is an option to limit the size of the dynamic processing in the config. 

I'm still working on performance issue of the image server, but now it's possible to use an external image server anyway.

**Comment by Daniel-KM** [comment]
This issue is fixed in last version (need last version of IIifServer, Generic, Universal Viewer).

**Comment by Daniel-KM** [comment]
About "Tify viewer", do you mean the chrome extension?
