### ISSUE TITLE
Deepzoom pretiled images don't load

### ISSUE THREAD

**Issue by jeau** [Daniel-KM/Omeka-S-module-ImageServer#4]
I am trying to migrate an installation that was working with the single IIF module with Deepzoom pretiled images. The media type "tile" is used for "ingester" and "renderer" fields of media table.

With the new module ImageServer the tiles are not loaded anymore  and apparently the rendering is calculated from original, obviously which causes  slowness.

**Comment by Daniel-KM** [comment]
It should be fixed.
